### ISSUE TITLE
Deployment mode

### ISSUE THREAD

**Issue by DobrolubovaJane** [j-barata/marketbasket-sbp-sample#3]
Hello! 

Could you please help me with deployment mode of SBP? I Added plugin jar and enabled, disabled files to plugins package, started my application in deployment mode, but had an error:

Field resourceProperties in org.springframework.boot.autoconfigure.web.servlet.PluginResourceHandlerRegistrationCustomizer required a bean of type 'org.springframework.boot.autoconfigure.web.ResourceProperties' that could not be found.

I have 2 questions:
1. How do you fix it? (I've seen you get it)
2. Should I take application.yaml for plugin to some different place from jar?

**Comment by dtrouillet** [comment]
Hi, I have same error. I have the same problem in development mode.

**Comment by dtrouillet** [comment]
@DobrolubovaJane , My problem is due to package name.
My App and my plugin share the same package name : this is my mistake.

**Comment by j-barata** [comment]
@DobrolubovaJane & @dtrouillet : thanks for your feedbacks

@DobrolubovaJane : do you confirm that the comment from @dtrouillet resolved your issue ?

**Comment by j-barata** [comment]
No feedback since many months.
I close it, feel free to re-open this issue if required.
